__title__ = "foliolib"
__description__ = "Okapi/Folio Manager and Library"
__url__ = "https://github.com/tobi-weber/foliolib"
__version__ = "0.2.0.a6"
__author__ = "Tobias Weber"
__author_email__ = "tobi-weber@gmx.de"
__license__ = "GNU General Public License v3 (GPLv3)"
__copyright__ = "Copyright 2022 Tobias Weber"
